Repository soowan95/prj2, pull requests merged in 2023-12, with the labels that each got.

#9 훈일 프론트 axios 경로수정
  src/page/main/MyPlayList.js
  src/page/main/RecommendedList.js
Labels: modify

#15 Feat/soowan/play song
  package-lock.json
  package.json
  src/component/PlayComp.js
  src/component/SongRequestComp.js
  src/index.js
  src/page/main/SongRequest.js
  src/page/main/Top100Page.js
Labels: feat

#19 Feat/mj/picture
  src/App.js
  src/component/KakaoLoginComp.js
  src/page/main/SongRequest.js
  src/page/memberLogin/MemberLogin.js
  src/page/song/SongList.js
  src/page/song/SongPage.js
Labels: feat

#20 Feat/euihyuk/myplaylist
  src/App.js
  src/page/main/ChartPage.js
  src/page/main/MyPlayList.js
  src/page/main/Suggestion.js
Labels: fix

#29 훈일 front 진행중
  src/App.js
  src/component/NavBar.js
  src/layout/HomeLayout.js
  src/page/main/MyFavoritePlaylist.js
  src/page/main/MyInfo.js
  src/page/main/MyPlayList.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/memberLogin/MemberInfo.js
  src/page/memberLogin/MemberLogin.js
  src/page/memberLogin/PasswordRecovery.js
Labels: feat

#28 Feat/soowan/song play
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/component/KakaoShareComp.js
  src/component/LiveChatComp.js
  src/component/LoginProvider.js
  src/component/NavBar.js
  src/component/PlayComp.js
  src/css/Scroll.css
  src/layout/MainLayout.js
  src/page/main/SearchPage.js
  src/page/main/Top100Page.js
  src/page/memberLogin/MemberLogin.js
  src/page/song/SongPage.js
  src/setupProxy.js
Labels: feat

#31 Feat/mj/picture1206
  src/App.js
  src/page/main/SongRequest.js
  src/page/song/SongEdit.js
  src/page/song/SongPage.js
Labels: feat

#32 Feat/euihyuk/1206
  src/page/main/ChartPage.js
  src/page/main/MyInfo.js
  src/page/main/MyPlayList.js
Labels: feat

#33 Feet/jeongwon/css
  src/component/CommentContainer.js
  src/component/PlayComp.js
  src/page/memberLogin/FoundPassword.js
  src/page/memberLogin/MemberLogin.js
  src/page/memberLogin/MemberSignup.js
  src/page/memberLogin/PasswordRecovery.js
Labels: feat

#38 Feat/hoonil/frontend 추천 플레이리스트
  src/App.js
  src/page/main/MyFavoritePlaylist.js
  src/page/main/MyInfo.js
  src/page/main/RecommendPlaylist.js
  src/page/main/RecommendedList.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/main/TopPlaylist.js
  src/page/memberLogin/MemberInfo.js
  src/page/memberLogin/MemberSignup.js
Labels: feat

#40 Feet/jeongwon/fix outlook
  src/App.js
  src/component/CommentContainer.js
  src/component/LoginProvider.js
  src/page/main/MySongRequest.js
  src/page/main/SongRequest.js
  src/page/main/Top100Page.js
  src/page/memberLogin/MemberInfo.js
  src/page/song/SongPage.js
Labels: feat

#43 Feat/mj/authenticate
  package-lock.json
  package.json
  src/component/NavBar.js
  src/page/main/SongRequest.js
  src/page/song/SongEdit.js
  src/page/song/SongPage.js
Labels: modify

#39 Feat/soowan/live chat
  package-lock.json
  package.json
  src/App.js
  src/component/LiveChatComp.js
  src/component/LoginProvider.js
  src/css/Home.css
  src/css/Scroll.css
  src/layout/HomeLayout.js
  src/layout/MainLayout.js
  src/page/memberLogin/KakaoLogin.js
  src/page/memberLogin/MemberLogin.js
  src/page/memberLogin/MemberSignup.js
Labels: feat

#47 Feet/jeongwon/complete song
  package-lock.json
  package.json
  public/img/background.jpg
  public/img/solidcolor.png
  src/component/CommentContainer.js
  src/css/Fonts.css
  src/index.js
  src/layout/MainLayout.js
  src/page/main/MySongRequest.js
  src/page/main/SearchPage.js
  src/page/song/SongPage.js
Labels: feat

#48 Feat/hoonil/playlist front
  src/App.js
  src/component/CommentContainer.js
  src/page/main/ChartPage.js
  src/page/main/MyPlayList.js
  src/page/main/TopPlaylist.js
  src/page/song/SongPage.js
Labels: feat

#50 Feat/mj/show more
  src/page/song/SongEdit.js
  src/page/song/SongPage.js
Labels: modify, feat

#51 feat/euihyuk/playlist 수정
  src/page/main/ChartPage.js
  src/page/main/MyFavoritePlaylist.js
  src/page/main/MyPlayList.js
  src/page/main/RecommendPlaylist.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/main/TopPlaylist.js
Labels: feat

#49 Modify/soowan/kakao login
  src/component/LiveChatComp.js
  src/component/LoginProvider.js
  src/css/Home.css
  src/css/Scroll.css
  src/layout/HomeLayout.js
  src/layout/MainLayout.js
  src/page/main/SearchPage.js
  src/page/main/Top100Page.js
  src/page/memberLogin/KakaoLogin.js
  src/page/memberLogin/MemberLogin.js
Labels: modify

#54 Fix/jeongwon/css
  public/img/Relieve.png
  public/img/Relieve2.png
  src/component/CommentContainer.js
  src/css/Fonts.css
  src/css/Home.css
  src/layout/HomeLayout.js
  src/layout/MainLayout.js
  src/page/song/SongPage.js
Labels: feat

#56 Feat/hoonil/create playlist frontend
  src/page/main/MyInfo.js
  src/page/song/SongPage.js
Labels: feat

#57 /feat/euihyuk/myplaylist css수정
  src/page/main/ChartPage.js
  src/page/main/MyPlayList.js
Labels: feat

#58 1215 pr
  src/component/LoginProvider.js
  src/index.js
  src/page/main/SongRequest.js
  src/page/song/SongEdit.js
Labels: modify

#52 Fix/soowan/update
  src/page/main/SongRequest.js
  src/page/memberLogin/MemberInfo.js
  src/page/memberLogin/MemberLogin.js
  src/page/memberLogin/MemberSignup.js
  src/page/memberLogin/PasswordRecovery.js
  src/page/song/SongEdit.js
Labels: fix

#60 mj css/top100페이지
  src/layout/HomeLayout.js
  src/page/main/SongRequest.js
  src/page/main/Top100Page.js
Labels: modify

#62 Feat/euihyuk/myplaylist ,recommendPlaylist css수정
  src/page/main/ChartPage.js
  src/page/main/MyPlayList.js
  src/page/main/RecommendPlaylist.js
Labels: modify

#64 playlist front hoonil
  src/page/main/ChartPage.js
  src/page/main/MyFavoritePlaylist.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/main/TopPlaylist.js
  src/page/song/SongPage.js
Labels: modify

#67 RecommenPlaylist, Chartpage css수정
  src/page/main/ChartPage.js
  src/page/main/MyPlayList.js
  src/page/main/RecommendPlaylist.js
Labels: modify

#68 mj css/search
  src/index.js
  src/page/main/SearchPage.js
Labels: modify

#69 Modify/jeongwon/css
  public/img/similar.png
  src/component/CommentContainer.js
  src/component/LiveChatComp.js
  src/css/Scroll.css
  src/layout/MainLayout.js
  src/page/song/SongPage.js
Labels: modify

#63 fix/플레이리스트 사진 안나오는 오류 수정
  src/App.js
  src/component/PlayComp.js
  src/layout/MainLayout.js
  src/page/main/ChartPage.js
  src/page/main/MyFavoritePlaylist.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/main/TopPlaylist.js
  src/page/memberLogin/MemberSignup.js
  src/page/song/SongPage.js
Labels: fix

#70 1218 front
  src/page/main/ChartPage.js
  src/page/main/RecommendPlaylist.js
  src/page/main/TopPlaylist.js
Labels: feat

#71 css 수정중..
  public/img/darkmode.jpg
  src/component/CommentContainer.js
  src/layout/MainLayout.js
  src/page/main/MySongRequest.js
  src/page/memberLogin/MemberInfo.js
  src/page/song/SongPage.js
Labels: modify

#72 mj css/hover
  src/component/PlayComp.js
  src/layout/MainLayout.js
  src/page/main/SearchPage.js
  src/page/main/Top100Page.js
Labels: modify

#73 Fix/soowan/playlist
  src/component/CommentContainer.js
  src/component/LiveChatComp.js
  src/page/main/MyInfo.js
  src/page/main/RecommendPlaylist.js
  src/page/main/SongRequest.js
  src/page/song/SongPage.js
Labels: fix

#75 feat/플레이리스트 카카오공유 기능 완료
  public/img/lightmode.jpg
  src/component/KakaoShareComp.js
  src/layout/MainLayout.js
  src/page/main/ChartPage.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/main/TopPlaylist.js
  src/page/song/SongPage.js
Labels: feat

#78 modify/플레이리스트 css수정
  src/page/main/ChartPage.js
  src/page/main/MyFavoritePlaylist.js
  src/page/main/MyPlayList.js
  src/page/main/RecommendPlaylist.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/main/TopPlaylist.js
Labels: modify

#80 css 수정
  public/img/RelieveBlack.png
  public/img/RelieveWhite.png
  public/img/RelieveYellow.png
  src/component/LiveChatComp.js
  src/layout/MainLayout.js
Labels: modify

#77 Modify/soowan/playlist
  package-lock.json
  package.json
  src/component/PlayComp.js
  src/page/main/MyPlayList.js
  src/page/main/RecommendPlaylist.js
Labels: modify

#82 1219 front finish
  src/page/main/TopPlaylist.js
Labels: fix

#83 modify/채팅창, 검색창 수정
  src/component/LiveChatComp.js
  src/layout/MainLayout.js
  src/page/main/RecommendPlaylist.js
  src/page/main/Top100Page.js
Labels: modify

#84 mj css/mainLayout
  src/layout/MainLayout.js
Labels: modify

#86 Dev
  package-lock.json
  package.json
  public/img/RelieveWhite.png
  public/img/RelieveYellow.png
  public/img/darkmode.jpg
  public/img/lightmode.jpg
  public/index.html
  src/App.js
  src/component/CommentContainer.js
  src/component/KakaoLoginComp.js
  src/component/KakaoShareComp.js
  src/component/LiveChatComp.js
  src/component/LoginProvider.js
  src/component/NavBar.js
  src/component/PlayComp.js
  src/component/SongRequestComp.js
  src/css/Fonts.css
  src/css/Home.css
  src/css/Scroll.css
  src/index.js
  src/layout/HomeLayout.js
  src/layout/MainLayout.js
  src/page/main/ChartPage.js
  src/page/main/MyFavoritePlaylist.js
  src/page/main/MyInfo.js
  src/page/main/MyPlayList.js
  src/page/main/MySongRequest.js
  src/page/main/RecommendPlaylist.js
  src/page/main/SearchPage.js
  src/page/main/SongInMyFavoritePlaylist.js
  src/page/main/SongRequest.js
  src/page/main/Suggestion.js
  src/page/main/Top100Page.js
  src/page/main/TopPlaylist.js
  src/page/memberLogin/FoundPassword.js
  src/page/memberLogin/KakaoLogin.js
  src/page/memberLogin/MemberDelete.js
  src/page/memberLogin/MemberInfo.js
  src/page/memberLogin/MemberLogin.js
  src/page/memberLogin/MemberSignup.js
  src/page/memberLogin/PasswordRecovery.js
  src/page/song/Counter.js
  src/page/song/SearchPage.js
  src/page/song/SongEdit.js
  src/page/song/SongList.js
  src/page/song/SongPage.js
  src/setupProxy.js
Labels: feat
